namespace Melon.Net.Http
{
    /// <summary>
    /// The http client interface, which should be inherited by clients that are generated by NSwag
    /// </summary>
    public interface IHttpClient
    {
    }
}